### ISSUE TITLE
Include Statement

### ISSUE THREAD

**Issue by Sammiches327** [andywer/php-easygit#1]
Just found this through Googling something and started using it. For some reason, when I installed through composter, the dir structure was `../vendor/easygit/easygit/EasyGit.php` rather than what's in the README file. Might be just how my system handled it...not sure. Thought I'd mention it ;)

**Comment by andywer** [comment]
Merged your PR :) Can we close the issue?

**Comment by Sammiches327** [comment]
Done :)
